### PR TITLE
Remove dash, s dependency

### PR DESCRIPTION
**Pull request by conao3**
Remove third party dependency.
Related #4.  As adding ELPA, it should have clean dependency.

### CODE REVIEW

**Comment by conao3** [comment]
How about this @rejeep? It is not minor change I think, I want to hear your intention.

**Comment by conao3** [comment]
Good, thanks!

**Comment by conao3** [comment]
Oops, i overlooked.
Why are you using `ansi--concat` instead of normal `concat`?

**Comment by conao3** [comment]
I find this testcase.
```
(ert-deftest test-ansi-concat ()
  (should (equal (ansi--concat "a" "b" "c") "abc"))
  (should (equal (ansi--concat "a" nil "c") "ac"))
  (should (equal (ansi--concat "a" 1 "c")   "ac")))
```
1st, 2nd testcase is reasonable. Because normal `concat` do the same thing.
But 3rd is odd to me. It should raise an error or return "a1c".

**Comment by rejeep** [comment]
I guess the main reason is to support case 3 so you can do `(ansi-red 10)`, but I don't remember. I probably wouldn't have done that now, but at the same time changing that now might break a lot of things. Bare in mind that this is one of the first Emacs things I did, so everything might not make  sense... 🙂

**Comment by conao3** [comment]
I think `cask` is a large user on this package.
But I cannot `make test` in `cask` repository. 
Can you help this?
```shell
$ git pull origin master
From github.com:cask/cask
 * branch            master     -> FETCH_HEAD
Already up to date.

$ git log --oneline | head -1
a4715f7 Merge pull request #469 from dajva/remove_stray_shutup_expr

$ cask
Loading package information... done
Package operations: 15 installs, 0 removals
  - Installing [ 1/15] ansi (0.4.1)... already present
  - Installing [ 2/15] package-build (1.2)... already present
  - Installing [ 3/15] cl-lib (0.3)... already present
  - Installing [ 4/15] shut-up (0.1.0)... already present
  - Installing [ 5/15] epl (0.5)... already present
  - Installing [ 6/15] f (0.16.0)... already present
  - Installing [ 7/15] dash (2.2.0)... already present
  - Installing [ 8/15] s (1.8.0)... already present
  - Installing [ 9/15] shell-split-string (latest)... already present
  - Installing [10/15] ert-async (latest)... already present
  - Installing [11/15] noflet (latest)... already present
  - Installing [12/15] el-mock (latest)... already present
  - Installing [13/15] ert-runner (latest)... already present
  - Installing [14/15] servant (latest)... already present
  - Installing [15/15] ecukes (latest)... already present

$ make test
cask exec ert-runner
Test cask-add-dependency-test/development backtrace:

Aborted: Ran 135 tests in 0.230 seconds
1 unexpected results:
   FAILED  cask-add-dependency-test/development
  UNKNOWN  cask-add-dependency-test/runtime
  UNKNOWN  cask-add-dependency-test/without-version
  ...
  UNKNOWN  cask-version-test
Cannot open load file: No such file or directory, cl-print
make: *** [Makefile:24: unit] Error 255

$ emacs --version
GNU Emacs 26.3
Copyright (C) 2019 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

$ cask version
0.8.4
```

**Comment by rejeep** [comment]
Good question, hard to tell without a stacktrace. It looks like there's a missing "require cl-print" in ert-runner, but I have no idea why that's not required via cl (I guess).

I don't really maintain my Emacs packages anymore and it seems they are in need of some love.

**Comment by conao3** [comment]
I try to get some backtrace, but I cannot get anything...

```
$ cask exec ert-runner --verbose --debug
Test cask-add-dependency-test/development backtrace:


Aborted: Ran 135 tests in 0.219 seconds
1 unexpected results:
   FAILED  cask-add-dependency-test/development
  UNKNOWN  cask-add-dependency-test/runtime
  UNKNOWN  cask-add-dependency-test/without-version
  ...
  UNKNOWN  cask-update-test/with-updates
  UNKNOWN  cask-version-test
Cannot open load file: No such file or directory, cl-print
```

> I don't really maintain my Emacs packages anymore and it seems they are in need of some love.

It is sad but I can help what I could do.

**Comment by rejeep** [comment]
> It is sad but I can help what I could do.

Yeah, it's difficult to find people to maintain Emacs packages. Any help would be appreciated because I don't have time myself, but it would be sad so see it deteriorate as well.

**Comment by Fuco1** [comment]
Both of these were already removed.

**Pull request closed without merging**
